spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
